### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/feathers#2]
I can't even get it to compile it on my machine. I think the include directories are wrong. Regardless the current make is clearly unacceptable and has to be replaced/update.

**Comment by riamon-v** [comment]
The compilation was a bit hard for me as well. Moreover we know that the make has to be replace. It was temporary, feel free to do it !

**Comment by riamon-v** [comment]
Is everything alright now ?

**Comment by Gaspard--** [comment]
Yes.
